services:
  base:
    image: ros2_kickstart:base
    container_name: ros2_kickstart
    build: 
      context: . 
      dockerfile: ./Dockerfile
      args:
        ROS_DISTRO: humble
      target: base
    stdin_open: true  
    tty: true
    # Networking and IPC for ROS 2
    network_mode: host
    ipc: host
    privileged: true         
    environment:
      - color_prompt=yes # Environment variable for colored prompts
      - DEBIAN_FRONTEND=noninteractive
      - LANG=en_US.UTF-8
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
      - QT_QTA_PLATFORM="xcb"
      - NVIDIA_VISIBLE_DEVICES=all # Makes all NVIDIA devices visible to the container
      - NVIDIA_DRIVER_CAPABILITIES=all # Grants all NVIDIA driver capabilities to the container
      - __NV_PRIME_RENDER_OFFLOAD=1 # Enables NVIDIA PRIME render offload
      - __GLX_VENDOR_LIBRARY_NAME=nvidia # Specifies the GLX vendor library to use (NVIDIA)
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
      - ./src:/workspace/src
      - ./notebooks:/workspace/notebooks
      - ./scripts:/workspace/scripts
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia  # Specify the runtime
